### ISSUE TITLE
Eliminar README'S  vacíos dentro de las carpetas

### ISSUE THREAD

**Issue by maggiemusa** [C1587S/OffenderDS#2]
Hola Sebas,

Hay README'S vacíos dentro de las siguientes carpetas: config, data y sentencias. Podrías quitarlos por favor.

Saludos y gracias

**Comment by C1587S** [comment]
Maggie, 

Ajustes realizados. Se eliminaron los tres README (fueron creados para crear las carpetas vacías).

Gracias.
