### ISSUE TITLE
Documenting functions in sentencias.py

### ISSUE THREAD

**Issue by dapivei** [C1587S/OffenderDS#27]
Hola Eli, falta documentar las funciones que tenemos en sentencias.py
@erodriguezul 

https://github.com/C1587S/OffenderDS/blob/master/sentencias/sentencias.py

**Comment by erodriguezul** [comment]
Hola Dani!
Ya documenté las funciones del .py, y también los .sql. 
Puedes revisarla en 
https://github.com/C1587S/OffenderDS/pull/31
Saludos!

**Comment by dapivei** [comment]
Ya lo vi, Eli. Me parece muy bien. Thanks.

**Comment by erodriguezul** [comment]
Ok, cierro el issue! Gracias!
