### ISSUE TITLE
Eliminación de documentos extras

### ISSUE THREAD

**Issue by maggiemusa** [C1587S/OffenderDS#37]
Hola Eli,

Podrías eliminar los documentos que están de más en las carpetas por favor.

Saludos

**Comment by erodriguezul** [comment]
Listo Maggie, 
acá el pull request:
https://github.com/C1587S/OffenderDS/pull/38

**Comment by maggiemusa** [comment]
Eli,

Se eliminaron las carpetas, podrías crearlas con un archivo vacío para que esté la estructura?

Saludos

**Comment by erodriguezul** [comment]
Nuevo pull request https://github.com/C1587S/OffenderDS/pull/39
