### ISSUE TITLE
Catálogo numdepen duplicado

### ISSUE THREAD

**Issue by erodriguezul** [C1587S/OffenderDS#7]
Hola Dani, 
Veo que tenemos el catálogo de numdepen duplicado, una vez como catalogo_numdepen.csv y otra como numdepen.csv.

¿Puedes eliminar este último, para conservar la nomenclatura?

**Comment by dapivei** [comment]
Hola Eli, no veo el documento. Lo puedes eliminar tú, please. Te mando el link de lo que veo. 

[https://github.com/C1587S/OffenderDS/tree/master/data](url)
